# Generated by Django 4.0.4 on 2022-05-02 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_req', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='ID')),
                ('text_answer', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('text_question', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания вопроса')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
